// This file was automatically generated by make-pins.py
//
// --af boards/mk64fn1M0xxx12_af.csv
// --board boards/frdmk64f/teensy_pins.csv
// --prefix boards/mk20dx256_prefix.c

// stm32fxx-prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>
#include <mk20dx128.h>

#include "py/obj.h"
#include "teensy_hal.h"
#include "pin.h"

#define AF(af_idx, af_fn, af_unit, af_type, af_ptr) \
{ \
    { &pin_af_type }, \
    .name = MP_QSTR_AF ## af_idx ## _ ## af_fn ## af_unit, \
    .idx = (af_idx), \
    .fn = AF_FN_ ## af_fn, \
    .unit = (af_unit), \
    .type = AF_PIN_TYPE_ ## af_fn ## _ ## af_type, \
    .af_fn = (af_ptr) \
}

#define PIN(p_port, p_pin, p_num_af, p_af, p_adc_num, p_adc_channel) \
{ \
    { &pin_type }, \
    .name = MP_QSTR_ ## p_port ## p_pin, \
    .port = PORT_ ## p_port, \
    .pin = (p_pin), \
    .num_af = (p_num_af), \
    .pin_mask = (1 << (p_pin)), \
    .gpio = GPIO ## p_port, \
    .af = p_af, \
    .adc_num = p_adc_num, \
    .adc_channel = p_adc_channel, \
}

const pin_af_obj_t pin_E0_af[] = {
  //( 0, ADC     ,  1, SE4a      , ADC1    ), // ADC1_SE4a
  //( 1, PTE     ,  0,           , PTE0    ), // PTE0
  //( 2, SPI     ,  1, PCS1      , SPI1    ), // SPI1_PCS1
  AF( 3, UART    ,  1, TX        , UART1   ), // UART1_TX
  //( 4, SDHC    ,  0, D1        , SDHC0   ), // SDHC0_D1
  //( 5, TRACE   ,  0, CLKOUT    , TRACE   ), // TRACE_CLKOUT
  AF( 6, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
  //( 7, RTC     ,  0, CLKOUT    , RTC     ), // RTC_CLKOUT
};

const pin_obj_t pin_E0 = PIN(E, 0, 2, pin_E0_af, 0, 0);

const pin_af_obj_t pin_A5_af[] = {
  //( 1, PTA     ,  5,           , PTA5    ), // PTA5
  //( 2, USB     ,  0, CLKIN     , USB     ), // USB_CLKIN
  AF( 3, FTM     ,  0, CH2       , FTM0    ), // FTM0_CH2
  //( 4, RMII    ,  0, RXER
MII0_RXER, RMII0   ), // RMII0_RXER
MII0_RXER
  //( 5, CMP     ,  2, OUT       , CMP2    ), // CMP2_OUT
  //( 6, I2S     ,  0, TX_BCLK   , I2S0    ), // I2S0_TX_BCLK
  //( 7, JTAG    ,  0, TRST_b    , JTAG    ), // JTAG_TRST_b
};

const pin_obj_t pin_A5 = PIN(A, 5, 1, pin_A5_af, 0, 0);

const pin_af_obj_t pin_A12_af[] = {
  //( 0, CMP     ,  2, IN0       , CMP2    ), // CMP2_IN0
  //( 1, PTA     , 12,           , PTA12   ), // PTA12
  //( 2, CAN     ,  0, TX        , CAN0    ), // CAN0_TX
  AF( 3, FTM     ,  1, CH0       , FTM1    ), // FTM1_CH0
  //( 4, RMII    ,  0, RXD1
MII0_RXD1, RMII0   ), // RMII0_RXD1
MII0_RXD1
  AF( 5, I2C     ,  2, SCL       , I2C2    ), // I2C2_SCL
  //( 6, I2S     ,  0, TXD0      , I2S0    ), // I2S0_TXD0
  AF( 7, FTM     ,  1, QD_PHA    , FTM1    ), // FTM1_QD_PHA
};

const pin_obj_t pin_A12 = PIN(A, 12, 3, pin_A12_af, 0, 0);

const pin_af_obj_t pin_B1_af[] = {
  //( 0, ADC     ,  0, SE9
ADC1_SE9, ADC0    ), // ADC0_SE9
ADC1_SE9
  //( 1, PTB     ,  1,           , PTB1    ), // PTB1
  AF( 2, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
  AF( 3, FTM     ,  1, CH1       , FTM1    ), // FTM1_CH1
  //( 4, RMII    ,  0, MDC
MII0_MDC, RMII0   ), // RMII0_MDC
MII0_MDC
  AF( 6, FTM     ,  1, QD_PHB    , FTM1    ), // FTM1_QD_PHB
};

const pin_obj_t pin_B1 = PIN(B, 1, 3, pin_B1_af, 0, 0);

const pin_af_obj_t pin_B2_af[] = {
  //( 0, ADC     ,  0, SE12      , ADC0    ), // ADC0_SE12
  //( 1, PTB     ,  2,           , PTB2    ), // PTB2
  AF( 2, I2C     ,  0, SCL       , I2C0    ), // I2C0_SCL
  //( 3, UART    ,  0, RTS_b     , UART0   ), // UART0_RTS_b
  //( 4, ENET    ,  0, 1588_TMR0 , ENET0   ), // ENET0_1588_TMR0
  //( 6, FTM     ,  0, FLT3      , FTM0    ), // FTM0_FLT3
};

const pin_obj_t pin_B2 = PIN(B, 2, 1, pin_B2_af, 0, 0);

const pin_af_obj_t pin_B3_af[] = {
  //( 0, ADC     ,  0, SE13      , ADC0    ), // ADC0_SE13
  //( 1, PTB     ,  3,           , PTB3    ), // PTB3
  AF( 2, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
  //( 3, UART    ,  0, CTS_b
UART0_COL_b, UART0   ), // UART0_CTS_b
UART0_COL_b
  //( 4, ENET    ,  0, 1588_TMR1 , ENET0   ), // ENET0_1588_TMR1
  //( 6, FTM     ,  0, FLT0      , FTM0    ), // FTM0_FLT0
};

const pin_obj_t pin_B3 = PIN(B, 3, 1, pin_B3_af, 0, 0);

const pin_af_obj_t pin_B16_af[] = {
  //( 1, PTB     , 16,           , PTB16   ), // PTB16
  //( 2, SPI     ,  1, SOUT      , SPI1    ), // SPI1_SOUT
  AF( 3, UART    ,  0, RX        , UART0   ), // UART0_RX
  //( 4, FTM     ,  0, CLKIN0    , FTM     ), // FTM_CLKIN0
  //( 5, FB      ,  0, AD17      , FB      ), // FB_AD17
  //( 6, EWM     ,  0, IN        , EWM     ), // EWM_IN
};

const pin_obj_t pin_B16 = PIN(B, 16, 1, pin_B16_af, 0, 0);

const pin_af_obj_t pin_B17_af[] = {
  //( 1, PTB     , 17,           , PTB17   ), // PTB17
  //( 2, SPI     ,  1, SIN       , SPI1    ), // SPI1_SIN
  AF( 3, UART    ,  0, TX        , UART0   ), // UART0_TX
  //( 4, FTM     ,  0, CLKIN1    , FTM     ), // FTM_CLKIN1
  //( 5, FB      ,  0, AD16      , FB      ), // FB_AD16
  //( 6, EWM     ,  0, OUT_b     , EWM     ), // EWM_OUT_b
};

const pin_obj_t pin_B17 = PIN(B, 17, 1, pin_B17_af, 0, 0);

const pin_af_obj_t pin_B18_af[] = {
  //( 1, PTB     , 18,           , PTB18   ), // PTB18
  //( 2, CAN     ,  0, TX        , CAN0    ), // CAN0_TX
  AF( 3, FTM     ,  2, CH0       , FTM2    ), // FTM2_CH0
  //( 4, I2S     ,  0, TX_BCLK   , I2S0    ), // I2S0_TX_BCLK
  //( 5, FB      ,  0, AD15      , FB      ), // FB_AD15
  AF( 6, FTM     ,  2, QD_PHA    , FTM2    ), // FTM2_QD_PHA
};

const pin_obj_t pin_B18 = PIN(B, 18, 2, pin_B18_af, 0, 0);

const pin_af_obj_t pin_B19_af[] = {
  //( 1, PTB     , 19,           , PTB19   ), // PTB19
  //( 2, CAN     ,  0, RX        , CAN0    ), // CAN0_RX
  AF( 3, FTM     ,  2, CH1       , FTM2    ), // FTM2_CH1
  //( 4, I2S     ,  0, TX_FS     , I2S0    ), // I2S0_TX_FS
  //( 5, FB      ,  0, OE_b      , FB      ), // FB_OE_b
  AF( 6, FTM     ,  2, QD_PHB    , FTM2    ), // FTM2_QD_PHB
};

const pin_obj_t pin_B19 = PIN(B, 19, 2, pin_B19_af, 0, 0);

// const pin_af_obj_t pin_C0_af[] = {
  //( 0, ADC     ,  0, SE14      , ADC0    ), // ADC0_SE14
  //( 1, PTC     ,  0,           , PTC0    ), // PTC0
  //( 2, SPI     ,  0, PCS4      , SPI0    ), // SPI0_PCS4
  //( 3, PDB     ,  0, EXTRG     , PDB0    ), // PDB0_EXTRG
  //( 4, USB     ,  0, SOF_OUT   , USB     ), // USB_SOF_OUT
  //( 5, FB      ,  0, AD14      , FB      ), // FB_AD14
  //( 6, I2S     ,  0, TXD1      , I2S0    ), // I2S0_TXD1
// };

const pin_obj_t pin_C0 = PIN(C, 0, 0, NULL, 0, 0);

const pin_af_obj_t pin_C2_af[] = {
  //( 0, ADC     ,  0, SE4b
CMP1_IN0, ADC0    ), // ADC0_SE4b
CMP1_IN0
  //( 1, PTC     ,  2,           , PTC2    ), // PTC2
  //( 2, SPI     ,  0, PCS2      , SPI0    ), // SPI0_PCS2
  //( 3, UART    ,  1, CTS_b     , UART1   ), // UART1_CTS_b
  AF( 4, FTM     ,  0, CH1       , FTM0    ), // FTM0_CH1
  //( 5, FB      ,  0, AD12      , FB      ), // FB_AD12
  //( 6, I2S     ,  0, TX_FS     , I2S0    ), // I2S0_TX_FS
};

const pin_obj_t pin_C2 = PIN(C, 2, 1, pin_C2_af, 0, 0);

// const pin_af_obj_t pin_C7_af[] = {
  //( 0, CMP     ,  0, IN1       , CMP0    ), // CMP0_IN1
  //( 1, PTC     ,  7,           , PTC7    ), // PTC7
  //( 2, SPI     ,  0, SIN       , SPI0    ), // SPI0_SIN
  //( 3, USB     ,  0, SOF_OUT   , USB     ), // USB_SOF_OUT
  //( 4, I2S     ,  0, RX_FS     , I2S0    ), // I2S0_RX_FS
  //( 5, FB      ,  0, AD8       , FB      ), // FB_AD8
// };

const pin_obj_t pin_C7 = PIN(C, 7, 0, NULL, 0, 0);

const pin_af_obj_t pin_C8_af[] = {
  //( 0, ADC     ,  1, SE4b
CMP0_IN2, ADC1    ), // ADC1_SE4b
CMP0_IN2
  //( 1, PTC     ,  8,           , PTC8    ), // PTC8
  AF( 3, FTM     ,  3, CH4       , FTM3    ), // FTM3_CH4
  //( 4, I2S     ,  0, MCLK      , I2S0    ), // I2S0_MCLK
  //( 5, FB      ,  0, AD7       , FB      ), // FB_AD7
};

const pin_obj_t pin_C8 = PIN(C, 8, 1, pin_C8_af, 0, 0);

const pin_af_obj_t pin_C9_af[] = {
  //( 0, ADC     ,  1, SE5b
CMP0_IN3, ADC1    ), // ADC1_SE5b
CMP0_IN3
  //( 1, PTC     ,  9,           , PTC9    ), // PTC9
  AF( 3, FTM     ,  3, CH5       , FTM3    ), // FTM3_CH5
  //( 4, I2S     ,  0, RX_BCLK   , I2S0    ), // I2S0_RX_BCLK
  //( 5, FB      ,  0, AD6       , FB      ), // FB_AD6
  //( 6, FTM     ,  2, FLT0      , FTM2    ), // FTM2_FLT0
};

const pin_obj_t pin_C9 = PIN(C, 9, 1, pin_C9_af, 0, 0);

const pin_af_obj_t pin_C10_af[] = {
  //( 0, ADC     ,  1, SE6b      , ADC1    ), // ADC1_SE6b
  //( 1, PTC     , 10,           , PTC10   ), // PTC10
  AF( 2, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
  AF( 3, FTM     ,  3, CH6       , FTM3    ), // FTM3_CH6
  //( 4, I2S     ,  0, RX_FS     , I2S0    ), // I2S0_RX_FS
  //( 5, FB      ,  0, AD5       , FB      ), // FB_AD5
};

const pin_obj_t pin_C10 = PIN(C, 10, 2, pin_C10_af, 0, 0);

const pin_af_obj_t pin_D1_af[] = {
  //( 0, ADC     ,  0, SE5b      , ADC0    ), // ADC0_SE5b
  //( 1, PTD     ,  1,           , PTD1    ), // PTD1
  AF( 2, SPI     ,  0, SCK       , SPI0    ), // SPI0_SCK
  //( 3, UART    ,  2, CTS_b     , UART2   ), // UART2_CTS_b
  AF( 4, FTM     ,  3, CH1       , FTM3    ), // FTM3_CH1
  //( 5, FB      ,  0, CS0_b     , FB      ), // FB_CS0_b
};

const pin_obj_t pin_D1 = PIN(D, 1, 2, pin_D1_af, 0, 0);

const pin_af_obj_t pin_D3_af[] = {
  //( 1, PTD     ,  3,           , PTD3    ), // PTD3
  //( 2, SPI     ,  0, SIN       , SPI0    ), // SPI0_SIN
  AF( 3, UART    ,  2, TX        , UART2   ), // UART2_TX
  AF( 4, FTM     ,  3, CH3       , FTM3    ), // FTM3_CH3
  //( 5, FB      ,  0, AD3       , FB      ), // FB_AD3
  AF( 7, I2C     ,  0, SDA       , I2C0    ), // I2C0_SDA
};

const pin_obj_t pin_D3 = PIN(D, 3, 3, pin_D3_af, 0, 0);

const pin_af_obj_t pin_D5_af[] = {
  //( 0, ADC     ,  0, SE6b      , ADC0    ), // ADC0_SE6b
  //( 1, PTD     ,  5,           , PTD5    ), // PTD5
  //( 2, SPI     ,  0, PCS2      , SPI0    ), // SPI0_PCS2
  //( 3, UART    ,  0, CTS_b
UART0_COL_b, UART0   ), // UART0_CTS_b
UART0_COL_b
  AF( 4, FTM     ,  0, CH5       , FTM0    ), // FTM0_CH5
  //( 5, FB      ,  0, AD1       , FB      ), // FB_AD1
  //( 6, EWM     ,  0, OUT_b     , EWM     ), // EWM_OUT_b
  AF( 7, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
};

const pin_obj_t pin_D5 = PIN(D, 5, 2, pin_D5_af, 0, 0);

const pin_af_obj_t pin_D7_af[] = {
  //( 1, PTD     ,  7,           , PTD7    ), // PTD7
  //( 2, CMT     ,  0, IRO       , CMT     ), // CMT_IRO
  AF( 3, UART    ,  0, TX        , UART0   ), // UART0_TX
  AF( 4, FTM     ,  0, CH7       , FTM0    ), // FTM0_CH7
  //( 6, FTM     ,  0, FLT1      , FTM0    ), // FTM0_FLT1
  //( 7, SPI     ,  1, SIN       , SPI1    ), // SPI1_SIN
};

const pin_obj_t pin_D7 = PIN(D, 7, 2, pin_D7_af, 0, 0);

STATIC const mp_map_elem_t pin_cpu_pins_locals_dict_table[] = {
  { MP_OBJ_NEW_QSTR(MP_QSTR_E0), (mp_obj_t)&pin_E0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A5), (mp_obj_t)&pin_A5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A12), (mp_obj_t)&pin_A12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B1), (mp_obj_t)&pin_B1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B2), (mp_obj_t)&pin_B2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B3), (mp_obj_t)&pin_B3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B16), (mp_obj_t)&pin_B16 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B17), (mp_obj_t)&pin_B17 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B18), (mp_obj_t)&pin_B18 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_B19), (mp_obj_t)&pin_B19 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C0), (mp_obj_t)&pin_C0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C2), (mp_obj_t)&pin_C2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C7), (mp_obj_t)&pin_C7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C8), (mp_obj_t)&pin_C8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C9), (mp_obj_t)&pin_C9 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_C10), (mp_obj_t)&pin_C10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D1), (mp_obj_t)&pin_D1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D3), (mp_obj_t)&pin_D3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D5), (mp_obj_t)&pin_D5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D7), (mp_obj_t)&pin_D7 },
};
MP_DEFINE_CONST_DICT(pin_cpu_pins_locals_dict, pin_cpu_pins_locals_dict_table);

STATIC const mp_map_elem_t pin_board_pins_locals_dict_table[] = {
  { MP_OBJ_NEW_QSTR(MP_QSTR_D0), (mp_obj_t)&pin_B16 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D1), (mp_obj_t)&pin_B17 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D3), (mp_obj_t)&pin_A12 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D5), (mp_obj_t)&pin_D7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D8), (mp_obj_t)&pin_D3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D12), (mp_obj_t)&pin_C7 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D14), (mp_obj_t)&pin_D1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D15), (mp_obj_t)&pin_C0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D17), (mp_obj_t)&pin_B1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D18), (mp_obj_t)&pin_B3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D19), (mp_obj_t)&pin_B2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D20), (mp_obj_t)&pin_D5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D23), (mp_obj_t)&pin_C2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D24), (mp_obj_t)&pin_A5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D25), (mp_obj_t)&pin_B19 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D27), (mp_obj_t)&pin_C9 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D28), (mp_obj_t)&pin_C8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D29), (mp_obj_t)&pin_C10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D31), (mp_obj_t)&pin_E0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_D32), (mp_obj_t)&pin_B18 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A0), (mp_obj_t)&pin_D1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A1), (mp_obj_t)&pin_C0 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A3), (mp_obj_t)&pin_B1 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A4), (mp_obj_t)&pin_B3 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A5), (mp_obj_t)&pin_B2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A6), (mp_obj_t)&pin_D5 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A9), (mp_obj_t)&pin_C2 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A16), (mp_obj_t)&pin_C9 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A17), (mp_obj_t)&pin_C8 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A18), (mp_obj_t)&pin_C10 },
  { MP_OBJ_NEW_QSTR(MP_QSTR_A20), (mp_obj_t)&pin_E0 },
};
MP_DEFINE_CONST_DICT(pin_board_pins_locals_dict, pin_board_pins_locals_dict_table);

const pin_obj_t * const pin_adc1[] = {
  NULL,    // 0
  NULL,    // 1
  NULL,    // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
};

const pin_obj_t * const pin_adc2[] = {
  NULL,    // 0
  NULL,    // 1
  NULL,    // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
};

const pin_obj_t * const pin_adc3[] = {
  NULL,    // 0
  NULL,    // 1
  NULL,    // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
};
